---
# tasks/install.yml (zabbix)
# Prefix : zabbix

- name: Pre-install packages
  apt:
    name: "gpg"
    state: present
    update_cache: yes

- name: Add apt repository for zabbix
  apt:
    deb: "{{ zabbix_repo_package }}"

- name: Install prerequirements
  apt:
    name: "{{ zabbix_install_packages }}"
    update_cache: True
    state: present

- name: Install zabbix-agent
  apt:
    name: "zabbix-agent"
    update_cache: True
    state: present

- name: Ensure zabbix-agent launches on boot
  systemd:
    name: zabbix-agent.service
    enabled: yes

- name: Install zabbix-api library
  pip:
    name: zabbix-api
