---

- name: Put UserParamater file
  template:
    src: userparameter_nginx.conf.j2
    dest: "{{ zabbix_agent_conf_dir }}/userparameter_nginx.conf"
    mode: "0644"
  notify: Restart zabbix-agent

- name: Create zabbix screen for Nginx
  zabbix_screen:
    screens:
      - screen_name: "{{ zabbix_agent_group_name }}::Nginx"
        host_group: "{{ zabbix_agent_group_name }}"
        graph_names:
          - "Nginx summary"
          - "Nginx connections"
        graph_width: 400
        graph_height: 100
    server_url: "{{ __zabbix_agent_kanshi_server_combined_info.url }}"
    login_user: admin
    login_password: "{{ __zabbix_agent_kanshi_server_combined_info.login_password }}"
  run_once: yes
